// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RoomMate_Finder.Infrastructure.Persistence;

#nullable disable

namespace RoomMate_Finder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112170000_AddUserActionsAndMatches_Retry")]
    partial class AddUserActionsAndMatches_Retry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This designer file was added to ensure EF Core discovers the migration.
            // The full model snapshot is available in AppDbContextModelSnapshot.
        }
    }
}

